import { StyleSheet } from "react-native";
import {
  Archivo_400Regular,
  Archivo_400Regular_Italic,
  Archivo_500Medium,
  Archivo_500Medium_Italic,
  Archivo_600SemiBold,
  Archivo_600SemiBold_Italic,
  Archivo_700Bold,
  Archivo_700Bold_Italic,
} from "@expo-google-fonts/archivo";

const styles = StyleSheet.create({
  welcomeSurface: {
    display: "flex",
    width: "100%",
    height: 150,
    backgroundColor: "#151515",
    borderRadius: 5,
    justifyContent: "center",
    paddingLeft: 20,
    paddingRight: 20,
    paddingBottom: 20,
    paddingTop: 30,
    marginTop: 10,
    marginBottom: 30,
    elevation: 1,
  },
  welcomeText: {
    fontFamily: "Archivo_500Medium",
    color: "#ffffff",
    fontSize: 16,
    textAlign: "left",
    lineHeight: 18,
  },
  homeScreen: {
    flex: 1,
    justifyContent: "space-around",
    backgroundColor: "#151515",
  },
  scrollView: {
    width: "100%",
  },
  stationBrowser: {
    display: "flex",
    width: "90%",
    justifyContent: "center",
    alignItems: "flex-start",
    flexDirection: "row",
    flexWrap: "wrap",
    marginTop: 20,
    marginBottom: 40,
  },
  browseHeader: {
    fontFamily: "Archivo_700Bold",
    fontSize: 18,
    color: "#ffffff",
    textAlign: "left",
    paddingLeft: 20,
    marginBottom: 20,
  },
  stationCard: {
    display: "flex",
    width: "100%",
    flexDirection: "row",
    flexWrap: "wrap",
    textAlign: "left",
    justifyContent: "flex-start",
    marginTop: 10,
    marginBottom: 10,
    paddingLeft: 20,
  },
  stationCardImage: {
    width: 70,
    height: 70,
    borderRadius: 2,
    marginTop: 5,
    marginRight: 12,
  },
  stationCardHeader: {
    fontFamily: "Archivo_500Medium",
    color: "#ffffff",
    textAlign: "left",
    fontSize: 16,
    marginBottom: 3,
  },
  stationCardInfo: {
    fontFamily: "Archivo_400Regular",
    color: "#ffffff",
    textAlign: "left",
    fontSize: 14,
    lineHeight: 18,
  },
  stationCardTextView: {
    display: "flex",
    width: "75%",
    alignContent: "flex-start",
  },
  stationThumbnail: {
    borderRadius: 2,
  },
  player: {
    fontFamily: "Archivo_700Bold",
    flexDirection: "row",
    padding: 0,
    margin: 0,
    height: 70,
    backgroundColor: "#282828",
    alignItems: "center",
    justifyContent: "space-between",
    elevation: 3,
  },
  playPauseIcon: {
    borderStyle: "solid",
    borderColor: "#e8e8e8",
    borderWidth: 1,
  },
  stationImage: {
    width: 70,
    height: 70,
  },
  stationInfo: {
    textAlign: "center",
    width: 220,
    padding: 0,
    justifyContent: "center",
  },
  stationInfoText: {
    fontFamily: "Archivo_600SemiBold",
    color: "#ffffff",
    fontSize: 16,
    margin: "auto",
    textAlign: "center",
  },
  scrollingTextContainer: {
    width: "100%",
    marginTop: 5,
  },
  scrollingText: {
    fontFamily: "Archivo_400Regular",
    color: "#ffffff",
    fontSize: 14,
  },
  control: {
    flexDirection: "row",
    width: 50,
    justifyContent: "flex-start",
    marginRight: 10,
  },
  customHeader: {
    display: "flex",
    backgroundColor: "#252525",
  },
  customHeaderText: {
    display: "flex",
    color: "#ffffff",
    fontFamily: "Archivo_700Bold",
    fontSize: 18,
    textAlign: "center",
  },
});

export default styles;
